### ISSUE TITLE
Use can-define to set up List and Map if they’re not passed in

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-realtime-rest-model#4]
This will make it possible to do the following:

```js
const connection = realtimeRestModel("/api/todos/{id}");

connection.Map // is a DefineMap.extend( { seal: false }, {} );
connection.List // is a DefineList.extend({ "#": {Type: connection.Map} });
```

Questions:

1. Is this the best module to do this in? `can-connect` already depends on can-define, maybe this new behavior should replace this? https://github.com/canjs/can-connect/blob/4f284fc8b9026767e7cf0f69968a94319b559f13/can/map/map.js#L43-L45
2. Should the map and list have debugging names like `DefineMap for {{url}}`?

**Comment by justinbmeyer** [comment]
Which can-connect modules depend on can-define?

**Comment by chasenlehara** [comment]
I only see `can/ref/ref` depending on `can-define` https://github.com/canjs/can-connect/blob/9f0c07f7e2d3b9d45d20ae0c51d1cad67e32ab50/can/ref/ref.js#L159

**Comment by chasenlehara** [comment]
Notes:

1. Yes, update this module, leave can-connect alone
2. Connections already take a `name` option, so that can be used to name the maps/lists.
